language: node_js
dist: xenial
sudo: required
addons:
  chrome: stable
services:
  - xvfb
node_js:
  - 'node'
  - 'lts/*'
cache:
  directories:
    - node_modules

before_script:
  - export DISPLAY=:99.0

script:
  - node ./internals/scripts/generate-templates-for-linting
  - npm test -- --maxWorkers=4
  - npm run build

after_success: 'npm run coveralls'

notifications:
  email:
    on_failure: change
